#
#	FileSystems
#
MAKE	=	make

main:
	@ ${MAKE} -C Template		-f GNUmakefile
	@ ${MAKE} -C ReiserFS		-f GNUmakefile
#	@ ${MAKE} -C BTRfs			-f GNUmakefile

clean:
	@ ${MAKE} -C Template		-f GNUmakefile clean
#	@ ${MAKE} -C BTRfs			-f GNUmakefile
	@ ${MAKE} -C ReiserFS		-f GNUmakefile
