#
#	'Polymorph.Library' Build Scripting
#
MAKE	=	make

main:
	@ ${MAKE} -C Template		-f GNUmakefile
	@ ${MAKE} -C WXP32			-f GNUmakefile
	@ ${MAKE} -C JavaVM			-f GNUmakefile
	@ ${MAKE} -C SmallTalkVM	-f GNUmakefile

clean:
	@ ${MAKE} -C Template		-f GNUmakefile clean
	@ ${MAKE} -C WXP32			-f GNUmakefile clean
	@ ${MAKE} -C JavaVM			-f GNUmakefile clean
	@ ${MAKE} -C SmallTalkVM	-f GNUmakefile clean
