#
#	'Polymorph.Library' Build Scripting
#
MAKE	=	make
RM		=	C:Delete ALL FORCE QUIET
DTW		=   Echo dtwrite

DataTypes: Windows
	Echo    DataTypes Descriptors Generated

Windows:
	Echo	"Windows 32bit Executable DataType Descriptor"
	$(DTW)	Windows.dtyp

clean:
	Echo    DataTypes Descriptors Cleaned
